config/routes.rb
Movingteachings::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  match "reload" => "application#reload"
  match 'teach' => 'dialectics#teach', as: 'teach'
  match 'learn' => 'dialectics#learn', as: 'learn'
  match 'share' => 'favorites#share', as: 'share'
  match 'learn/:id' => 'dialectics#show', as: 'show_dialectic'
  match 'welcome/intro' => 'welcome#intro', as: 'intro'
  
  match 'users/loggedIn' => 'users#loggedIn'
  match 'welcome/login' => 'welcome#login'
  match "books/search" => "books#search"

  resources :favorites do
    collection do
      get :starred
      get :share
    end
  end
  resources :stops
  resources :routes do
    member do
      get :dialectics
      get :stops
    end
    collection do
      get :alternatives
      get :samples
      get :tmpl
    end
  end
  resources :locations do
    member do
      get :routes
    end
    collection do
      post :submit_request
    end
  end
  resources :dialectics do
    collection do
      get :mine
    end
    member do
      post :register
    end
  end

  match 'locations/:id/:route_id' => 'locations#show'

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  root :to => 'welcome#index'

end

app/views/layouts/_common.html.haml
%h4 Connect with people. Learn things. Listen. Teach.
.ng-view

app/views/layouts/_fb.html.haml
#fb-root
:javascript
  (function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=286149531487221";
  fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/layouts/_ga.html.haml
:javascript
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-35638153-1']);
  _gaq.push(['_setDomainName', 'movingteachings.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type =
    'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' :
    'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0];
    s.parentNode.insertBefore(ga, s);
  })();

app/views/layouts/_og.html.haml
<!-- meta property="og:image" content="http://movingteachings.com"/ -->
<meta property="og:title" content="Moving Teachings: Connect, expand and learn. On the bus."/>
<meta property="og:url" content="http://movingteachings.com"/>
<meta property="og:site_name" content="MovingTeachings.com"/>
<meta property="og:type" content=""/>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Moving Teachings: take mini classes (on the bus)
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    =# javascript_include_tag "http://maps.googleapis.com/maps/api/js?sensor=false"
    = javascript_include_tag "http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false"
    = csrf_meta_tags

    = render partial: 'layouts/og'
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
    = render partial: 'layouts/ga'
  %body{ 'ng-app' => 'movingteachings', 'ng-controller' => "MainCtrl" }
    = render partial: 'layouts/fb'

    .navbar.navbar-inverse.navbar-fixed-top
      .navbar-inner
        .container-fluid
          %a.brand{ href: '/' } Moving Teachings
          %ul.nav
            - if current_user
              %li= link_to "Register", learn_path()
              %li= link_to "Teach", teach_path()
              %li= link_to "Favorites", favorites_path()
          %ul.nav.pull-right
            - if current_user
              %li.hidden-phone
                %a
                  = current_user.name
                  - if current_user.provider.eql?( "facebook" )
                    %img{ src: "/assets/#{current_user.provider}.png" }
              %li.hidden-phone= link_to "Logout", destroy_user_session_path(), :method => :delete
              %li.visible-phone.pull-right{ 'ng-click' => 'logout()' }
                %i.icon-off
                %a
            - else 
              %li.hidden-phone= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook)
              %li.hidden-phone= link_to "Sign in with Google", user_omniauth_authorize_path(:google_oauth2)
              %li.visible-phone= link_to "Facebook", user_omniauth_authorize_path(:facebook)
              %li.visible-phone= link_to "Google", user_omniauth_authorize_path(:google_oauth2)

    .container.movingteachings
      = yield
      = render partial: 'layouts/common'

    